- name: Installing_jenkins
  hosts: all
  become: yes
  tasks:
  - name: Copying_jenkisscripts
    copy:
      src: jenkinscript.sh
      dest: /home/ubuntu
  - name: shell_jenkinscript
    shell: sh /home/ubuntu/jenkinscript.sh
