---
 - name: Valutpassword_playbook
   hosts: all
   tasks:
    - name: copy_module
      copy:
        src: /root/file2
        dest: /root
    - name: Shell_commands
      shell: cat file2
      register: target_cat
    - debug: 
        var: target_cat.stdout_lines 


